/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

/**
 * MainTest
 */
public class MainTest
{

    @Test public void foo()
    {
        Main m = new Main();
        assert m.returnStringForTest() == "Preparing TP2";
    }
}
