package org.example;

/*
 * This source file was generated by the Gradle 'init' task.
 */

import org.junit.jupiter.api.Test;

/**
 * MainTest class.
 */
public class MainTest
{

    @Test
    public void foo()
    {
        Main m = new Main();
        assert m.returnStringForTest() == "Preparing TP2";
    }
}
