#!/bin/bash

set -e
shopt -s globstar

cd TP2

echo -e "\n------------------------------\n"
echo -e "Running spell checkers"
echo -e "\n------------------------------\n"
docker run --rm -v "$PWD":/app:Z cspell -c /app/.cspell.json --file **/*.java
docker run --rm -v "$PWD":/app:Z cspell -c /app/.cspell.json --file **/*.md

echo -e "\n------------------------------\n"
echo -e "Runnig Style Checker"
echo -e "\n------------------------------\n"
./gradlew checkstyleMain
./gradlew checkstyleTest
./gradlew spotlessCheck

echo -e "\n------------------------------\n"
echo -e "Runnig Tests"
echo -e "\n------------------------------\n"
./gradlew clean test jacocoTestCoverageVerification

