name: TP-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "dev", "main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run style checking
        run: |
          sudo rm -rf /usr/bin/clang-format || echo "No /usr/bin/clang-format present"
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.7/LLVM-21.1.7-Linux-X64.tar.xz
          tar -xf LLVM-21.1.7-Linux-X64.tar.xz
          sudo ln -s LLVM-21.1.7-Linux-X64/bin/clang-format /usr/bin/clang-format
          cd TP2
          gradle spotlessCheck

      - name: Run tests
        run: |
          cd TP2
          gradle test jacocoTestCoverageVerification

      - name: Run cspell
        run: |
          docker build -t cspell -f ./.extras/Dockerfile/cspell.dockerfile .
          bash -c 'shopt -s globstar; docker run --rm -v "$PWD":/app cspell -c TP2/.cspell.json --file TP2/**/*.java'
          bash -c 'shopt -s globstar; docker run --rm -v "$PWD":/app cspell -c TP2/.cspell.json --file TP2/**/*.md'
