name: TP-CI

on:
  workflow_dispatch:
  pull_request:
    branches: ["dev","main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Repository check
        uses: ./.github/actions/repository

      - name: Run style check
        uses: ./.github/actions/style

      - name: Run testing
        uses: ./.github/actions/tests

      - name: Run spelling checks
        uses: ./.github/actions/spelling

      - name: Run build process
        uses: ./.github/actions/building

