name: Run Tests

on:
  workflow_call:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          cd TP2
          gradle test jacocoTestCoverageVerification
